name: madj2k/stage
prefixType: vendor # prefixing with vendor for reuse of database fields
fields:
  - identifier: madj2k/header
    type: Basic
  - identifier: madj2k/bodytext-reduced
    type: Basic
  - identifier: tab-media
    type: Tab
  - identifier: madj2k/assets-single
    type: Basic
