name: madj2k/banner
prefixType: vendor # prefixing with vendor for reuse of database fields
fields:
  - identifier: madj2k/background-color-extended
    type: Basic
  - identifier: madj2k/palette-header
    type: Basic
  - identifier: madj2k/palette-cta
    type: Basic
