name: madj2k/accordion
prefixType: vendor # prefixing with vendor for reuse of database fields
fields:
  - identifier: accordion_items
    type: Collection
    minitems: 1
    foreign_table: tt_content
    allowedRecordTypes:
      - madj2k_accordionitem
    appearance:
      levelLinksPosition: both
    overrideChildTca:
      columns:
        CType:
          config:
            default: madj2k_accordionitem
